### ISSUE TITLE
still spawn problems with fabric 1.20.1 and mod ver. 1.2.0

### ISSUE THREAD

**Issue by 3dEADto2** [whiteheket/More-Crustacean#1]
I still have massive spawn problems with crabs. If I'm in a biome that borders an ocean, an infinite number of crabs spawn in the ocean biome.

[screenshot](https://imgur.com/rWiwsWC)

**Comment by whiteheket** [comment]
I  am so sorry I dont konw why this could happen :c  Is this situation always happen? In my test these crabs always spawn less than vanilla fish because thier spawn weight are less than vanilla fish(vanilla fish are  25 and all kind of crabs are 5). Can you give me more information?

**Comment by whiteheket** [comment]
> I still have massive spawn problems with crabs. If I'm in a biome that borders an ocean, an infinite number of crabs spawn in the ocean biome.
> 
> [screenshot](https://imgur.com/rWiwsWC)
I am so sorry I dont konw why this could happen :c Is this situation always happen? In my test these crabs always spawn less than vanilla fish because thier spawn weight are less than vanilla fish(vanilla fish are 25 and all kind of crabs are 5). Can you give me more information?

**Comment by whiteheket** [comment]
> I still have massive spawn problems with crabs. If I'm in a biome that borders an ocean, an infinite number of crabs spawn in the ocean biome.
> 
> [screenshot](https://imgur.com/rWiwsWC)

I've tested many places ,the crabs spawn can be only 2~5 and vanilla fishes are about 25.  It may happen by accident . :c I really dont know how could these happen. Maybe you can leave this place to other places and then they will despawn.

**Comment by 3dEADto2** [comment]
Yes, they start to despawn again when you get close to them, but very slowly. I made a short clip showing how I can always cause the error very reliably. Maybe that will help. The adjacent biome doesn't matter, as long as it borders an ocean biome.

I will also upload my modlist.

[Video](https://youtu.be/DYCyaij9OSc)
![spawnerror m](https://github.com/whiteheket/More-Crustacean/assets/110291809/be1f13a7-d253-419d-b4cb-5282f2098911)

[modlist.txt](https://github.com/user-attachments/files/15796227/modlist.txt)

**Comment by whiteheket** [comment]
> Yes, they start to despawn again when you get close to them, but very slowly. I made a short clip showing how I can always cause the error very reliably. Maybe that will help. The adjacent biome doesn't matter, as long as it borders an ocean biome.
> 
> I will also upload my modlist.
> 
> [Video](https://youtu.be/DYCyaij9OSc) ![spawnerror m](https://private-user-images.githubusercontent.com/110291809/338784082-be1f13a7-d253-419d-b4cb-5282f2098911.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg0NzIsIm5iZiI6MTcxODE1ODE3MiwicGF0aCI6Ii8xMTAyOTE4MDkvMzM4Nzg0MDgyLWJlMWYxM2E3LWQyNTMtNDE5ZC1iNGNiLTUyODJmMjA5ODkxMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjYwNWZjZjBmMjI4MThmMjg4M2U3ZGQxOGJlZjM4ODhjMjgzYjQwOWMzNjM0YzE3MGEyZGFjODIzMmYzZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p85WINZWPvP7A6SImK886Q51duaEDRrC4TtraovPEps) [ ![spawnerror m](https://private-user-images.githubusercontent.com/110291809/338784082-be1f13a7-d253-419d-b4cb-5282f2098911.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg0NzIsIm5iZiI6MTcxODE1ODE3MiwicGF0aCI6Ii8xMTAyOTE4MDkvMzM4Nzg0MDgyLWJlMWYxM2E3LWQyNTMtNDE5ZC1iNGNiLTUyODJmMjA5ODkxMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjYwNWZjZjBmMjI4MThmMjg4M2U3ZGQxOGJlZjM4ODhjMjgzYjQwOWMzNjM0YzE3MGEyZGFjODIzMmYzZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p85WINZWPvP7A6SImK886Q51duaEDRrC4TtraovPEps) ](https://private-user-images.githubusercontent.com/110291809/338784082-be1f13a7-d253-419d-b4cb-5282f2098911.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg0NzIsIm5iZiI6MTcxODE1ODE3MiwicGF0aCI6Ii8xMTAyOTE4MDkvMzM4Nzg0MDgyLWJlMWYxM2E3LWQyNTMtNDE5ZC1iNGNiLTUyODJmMjA5ODkxMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjYwNWZjZjBmMjI4MThmMjg4M2U3ZGQxOGJlZjM4ODhjMjgzYjQwOWMzNjM0YzE3MGEyZGFjODIzMmYzZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p85WINZWPvP7A6SImK886Q51duaEDRrC4TtraovPEps) [ ](https://private-user-images.githubusercontent.com/110291809/338784082-be1f13a7-d253-419d-b4cb-5282f2098911.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg0NzIsIm5iZiI6MTcxODE1ODE3MiwicGF0aCI6Ii8xMTAyOTE4MDkvMzM4Nzg0MDgyLWJlMWYxM2E3LWQyNTMtNDE5ZC1iNGNiLTUyODJmMjA5ODkxMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjYwNWZjZjBmMjI4MThmMjg4M2U3ZGQxOGJlZjM4ODhjMjgzYjQwOWMzNjM0YzE3MGEyZGFjODIzMmYzZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p85WINZWPvP7A6SImK886Q51duaEDRrC4TtraovPEps)
> 
> [modlist.txt](https://github.com/user-attachments/files/15796227/modlist.txt)

Can you send me your modpack?_(:з」∠)_ i wanna try it

**Comment by 3dEADto2** [comment]
I use the modrinth launcher. that's why this is a modrinth .mrpack file. 
[modrinth file](https://www.mediafire.com/file/39emxipgijqfo8v/Exploration_%2526_More_6.6.6.mrpack/file)

**Comment by whiteheket** [comment]
> I use the modrinth launcher. that's why this is a modrinth .mrpack file. [modrinth file](https://www.mediafire.com/file/39emxipgijqfo8v/Exploration_%2526_More_6.6.6.mrpack/file)

I have same problem with you now 😢 And I dont know why this could happen because I am just following vanilla creature spawn. I will try to fix it in later version but not this time .Sorry 😢

**Comment by whiteheket** [comment]
> I use the modrinth launcher. that's why this is a modrinth .mrpack file. [modrinth file](https://www.mediafire.com/file/39emxipgijqfo8v/Exploration_%2526_More_6.6.6.mrpack/file)

I fix it now . And I try it in your modpack .It is works well in vanilla fabric version, but maybe too less in your modpack (But i think it doesnt matter)🥲 Thanks for your feedback (My English is not very well)

**Comment by 3dEADto2** [comment]
> > I use the modrinth launcher. that's why this is a modrinth .mrpack file. [modrinth file](https://www.mediafire.com/file/39emxipgijqfo8v/Exploration_%2526_More_6.6.6.mrpack/file)
> 
> I fix it now . And I try it in your modpack .It is works well in vanilla fabric version, but maybe too less in your modpack (But i think it doesnt matter)🥲 Thanks for your feedback (My English is not very well)

Take your time. Until it's fixed, I'll disable the spawning of crabs and add them to the fishing loot pool.

**Comment by whiteheket** [comment]
> > > I use the modrinth launcher. that's why this is a modrinth .mrpack file. [modrinth file](https://www.mediafire.com/file/39emxipgijqfo8v/Exploration_%2526_More_6.6.6.mrpack/file)
> > 
> > 
> > I fix it now . And I try it in your modpack .It is works well in vanilla fabric version, but maybe too less in your modpack (But i think it doesnt matter)🥲 Thanks for your feedback (My English is not very well)
> 
> Take your time. Until it's fixed, I'll disable the spawning of crabs and add them to the fishing loot pool.

fix in new version

**Comment by 3dEADto2** [comment]
I tested fixed-2. Now nothing spawns anymore. Neither crabs nor mussels o.O

Edit: OK, they now spawn very, very, very rarely. Is that intentional? It took 20 minutes for a crab to spawn.

**Comment by whiteheket** [comment]
> I tested fixed-2. Now nothing spawns anymore. Neither crabs nor mussels o.O
> 
> Edit: OK, they now spawn very, very, very rarely. Is that intentional? It took 20 minutes for a crab to spawn.

I think it is your modpack have too many ocean biomes or maybe you have change ambient creature's spawn. These crab can spawn only in vanilla ocean and they are ambient creatures not water_ambient creatures now. This change makes them spawn normal in vanilla fabric version and my modpack. This is what i cando in these times. I will try to add config and tag in future version .

**Comment by 3dEADto2** [comment]
That's ok. I'll just add them to the fishing loot pool, then you can fish for them. And thanks for your work =)
