### ISSUE TITLE
Xian potion effect

### ISSUE THREAD

**Issue by PetiPuss** [whiteheket/More-Crustacean#2]
Hi! 
Sorry to bother, but i was just wondering what does the Xian potion effect do? Can't seem to figure out what it does. :(

**Comment by whiteheket** [comment]
> Hi! Sorry to bother, but i was just wondering what does the Xian potion effect do? Can't seem to figure out what it does. :(

Sorry I am in rest these months and i havent seen this quickly .This effect needs farmers delight to work. It will make some vanilla status effect (speed or strength and some else) to a high level (Xian level+1)

**Comment by whiteheket** [comment]
> Hi! Sorry to bother, but i was just wondering what does the Xian potion effect do? Can't seem to figure out what it does. :(

Sorry I am in rest these months and i havent seen this quickly .This effect needs farmers delight to work. It will make some vanilla status effect (speed or strength and some else) to a high level (Xian level+1)
